workflows:
  working-ipa:
    name: Working IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fix Dependencies First
        script: |
          echo "=== FIXING DEPENDENCIES ==="
          # Update pubspec to resolve version conflicts
          flutter pub deps
      - name: Create iOS Project
        script: |
          echo "=== CREATING iOS PROJECT ==="
          flutter create --org com.hello.app --platforms=ios --overwrite .
          echo "=== VERIFYING ==="
          ls -la ios/Runner.xcodeproj/ && echo "✅ iOS PROJECT READY!"
      - name: Get Dependencies
        script: |
          echo "=== GETTING DEPENDENCIES ==="
          flutter pub get --verbose
      - name: Build IPA
        script: |
          echo "=== BUILDING IPA ==="
          flutter build ipa --no-codesign
          echo "=== CHECKING ARTIFACTS ==="
          ls -la build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa