workflows:
  final-ipa:
    name: Final IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          flutter create --org com.final.app --platforms=ios --overwrite .
          flutter pub get
          flutter build ipa --no-codesign
          echo "✅ IPA FILE CREATED - READY FOR DOWNLOAD!"
    artifacts:
      - build/ios/ipa/*.ipa