
workflows:
  manual-ios-ipa:
    name: Manual iOS IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Manual iOS Setup
        script: |
          echo "=== Manual iOS Project Creation ==="
          
          # Completely clean
          rm -rf ios
          
          # Create using Flutter template
          flutter create --template=app --platforms=ios --org com.example.helloapp --overwrite .
          
          # Force iOS project generation
          cd ios
          pod install || echo "CocoaPods might not be needed"
          cd ..
          
          echo "=== Final verification ==="
          if [ -d "ios/Runner.xcodeproj" ]; then
            echo "✅ iOS project verified!"
          else
            echo "❌ iOS project missing - attempting recovery..."
            flutter create --platforms=ios .
          fi
      - name: Build and Test
        script: |
          flutter pub get
          echo "=== Building IPA ==="
          flutter build ipa --no-codesign 2>&1 | tee build_log.txt
          
          echo "=== Build log summary ==="
          tail -20 build_log.txt
          
          echo "=== Artifact search ==="
          find . -name "*.ipa" -type f
    artifacts:
      - build/ios/ipa/*.ipa
      - build_log.txt