workflows:
  download-ipa:
    name: Download IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Create iOS Project
        script: |
          echo "=== STEP 1: Creating iOS Project ==="
          flutter create --org com.download.app --platforms=ios --overwrite .
          echo "✅ iOS project created"
      - name: Get Dependencies
        script: |
          echo "=== STEP 2: Getting Dependencies ==="
          flutter pub get
          echo "✅ Dependencies loaded"
      - name: Build IPA
        script: |
          echo "=== STEP 3: Building IPA ==="
          flutter build ipa --no-codesign
          echo "✅ IPA build completed"
      - name: Verify IPA
        script: |
          echo "=== STEP 4: Verifying IPA File ==="
          ls -la build/ios/ipa/
          echo "📱 IPA FILE READY FOR DOWNLOAD!"
    artifacts:
      - build/ios/ipa/*.ipa