workflows:
  emergency-ipa:
    name: Emergency IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Complete Fresh Start
        script: |
          echo "=== EMERGENCY MODE ==="
          
          # Save your source code
          mkdir -p /tmp/source_backup
          cp -r lib pubspec.yaml codemagic.yaml /tmp/source_backup/
          
          # Complete clean slate
          rm -rf *
          
          # Restore source code
          cp -r /tmp/source_backup/* .
          
          # Create fresh project
          flutter create --org com.example.emergency --platforms=ios --overwrite .
          
          echo "=== Emergency verification ==="
          ls -la ios/Runner.xcodeproj/ && echo "SUCCESS" || echo "FAILED"
      - name: Build IPA
        script: |
          flutter pub get
          flutter build ipa --no-codesign
          echo "IPA build attempt completed"
          ls -la build/ios/ipa/ 2>/dev/null || find build/ -name "*.ipa" 2>/dev/null
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/**/*