workflows:
  simple-ipa:
    name: Simple IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Create project
        script: |
          flutter create --org com.example.helloapp --platforms=ios --overwrite .
      - name: Build IPA
        script: |
          flutter pub get
          flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa