# Save this as codemagic.yaml in your project root
workflows:
  artifact-check:
    name: Artifact Check
    environment:
      flutter: stable
    scripts:
      - name: Check Environment
        script: |
          echo "Current directory:"
          pwd
          echo "Creating test artifacts..."
          mkdir -p output
          echo "SUCCESS" > output/build_success.txt
          ls -la > output/file_list.txt
          echo "If you see this in artifacts, it's working!" > output/readme.txt
          ls -la output/
    artifacts:
      - output/**/*
      - output/*