workflows:
  guaranteed-ipa:
    name: Guaranteed IPA Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Force Create iOS Project
        script: |
          echo "=== STEP 1: Force creating iOS project ==="
          flutter create --org com.yourcompany.hello --platforms=ios --overwrite .
          
          echo "=== STEP 2: Verify iOS project ==="
          if [ -d "ios/Runner.xcodeproj" ]; then
            echo "✅ iOS PROJECT CREATED SUCCESSFULLY!"
          else
            echo "❌ iOS project missing - using emergency method"
            # Emergency fallback
            mkdir -p ios
            flutter create --platforms=ios --overwrite .
          fi
          
          echo "=== STEP 3: Final verification ==="
          find . -name "*.xcodeproj" | head -5
      - name: Build IPA
        script: |
          echo "=== STEP 4: Building IPA ==="
          flutter clean
          flutter pub get
          flutter build ipa --no-codesign --verbose
          
          echo "=== STEP 5: Checking for IPA ==="
          find . -name "*.ipa" -type f
          ls -la build/ios/ipa/ || echo "Listing build directory..."
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log